// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy8-0GLH1ud9aTferObY_CXUKdEVH2sqw',
    appId: '1:281872993452:web:a308280e9a762fc8166309',
    messagingSenderId: '281872993452',
    projectId: 'safetyguardian-8a895',
    authDomain: 'safetyguardian-8a895.firebaseapp.com',
    storageBucket: 'safetyguardian-8a895.firebasestorage.app',
    measurementId: 'G-RH1E60K2M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDRourswh7y4rzVxDkDkvOHDhI4LXjQi0',
    appId: '1:281872993452:android:5413033d6c3c6200166309',
    messagingSenderId: '281872993452',
    projectId: 'safetyguardian-8a895',
    storageBucket: 'safetyguardian-8a895.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzzOCVgYrmtn0-l2UYXs8WehZI1SY0sLw',
    appId: '1:281872993452:ios:68b65ba37701a301166309',
    messagingSenderId: '281872993452',
    projectId: 'safetyguardian-8a895',
    storageBucket: 'safetyguardian-8a895.firebasestorage.app',
    iosBundleId: 'com.example.safetyGuardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzzOCVgYrmtn0-l2UYXs8WehZI1SY0sLw',
    appId: '1:281872993452:ios:68b65ba37701a301166309',
    messagingSenderId: '281872993452',
    projectId: 'safetyguardian-8a895',
    storageBucket: 'safetyguardian-8a895.firebasestorage.app',
    iosBundleId: 'com.example.safetyGuardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy8-0GLH1ud9aTferObY_CXUKdEVH2sqw',
    appId: '1:281872993452:web:c316b4324050fe78166309',
    messagingSenderId: '281872993452',
    projectId: 'safetyguardian-8a895',
    authDomain: 'safetyguardian-8a895.firebaseapp.com',
    storageBucket: 'safetyguardian-8a895.firebasestorage.app',
    measurementId: 'G-YL9SMXN0N8',
  );
}
